import 'package:flutter/material.dart';
import '../../../core/constants/colors.dart';
import '../../../data/models/user_dto.dart';
import '../../../data/services/firestore.dart';

class RegisterPage extends StatefulWidget {
  const RegisterPage({super.key});

  @override
  State<RegisterPage> createState() => _RegisterPageState();
}

class _RegisterPageState extends State<RegisterPage> {
  final _formKey = GlobalKey<FormState>();
  final TextEditingController _emailController = TextEditingController();
  final TextEditingController _firstNameController = TextEditingController();
  final TextEditingController _lastNameController = TextEditingController();
  final TextEditingController _phoneController = TextEditingController();
  final TextEditingController _birthYearController = TextEditingController();
  final TextEditingController _genderController = TextEditingController();
  final TextEditingController _profileController = TextEditingController();
  final TextEditingController _photoUrlController = TextEditingController();

  final FirestoreService _firestoreService = FirestoreService();

  void _registerUser() async {
    if (_formKey.currentState!.validate()) {
      final user = User(
        uid: '', // UID will be generated by Firestore
        birthYear: int.tryParse(_birthYearController.text) ?? 0,
        email: _emailController.text,
        firstName: _firstNameController.text,
        gender: _genderController.text,
        lastName: _lastNameController.text,
        phone: _phoneController.text,
        profiles: [_profileController.text],
        photoUrl: _photoUrlController.text.isNotEmpty ? _photoUrlController.text : null,
      );
      await _firestoreService.addUser(user);
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Usuario registrado correctamente')),
      );
      // Puedes navegar a otra página aquí
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Registro de Usuario')),
      body: Center(
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(20),
          child: Form(
            key: _formKey,
            child: Column(
              children: [
                TextFormField(
                  controller: _emailController,
                  decoration: const InputDecoration(labelText: 'Email'),
                  validator: (value) => value == null || value.isEmpty ? 'Introduce tu email' : null,
                ),
                TextFormField(
                  controller: _firstNameController,
                  decoration: const InputDecoration(labelText: 'Nombre'),
                  validator: (value) => value == null || value.isEmpty ? 'Introduce tu nombre' : null,
                ),
                TextFormField(
                  controller: _lastNameController,
                  decoration: const InputDecoration(labelText: 'Apellidos'),
                  validator: (value) => value == null || value.isEmpty ? 'Introduce tus apellidos' : null,
                ),
                TextFormField(
                  controller: _phoneController,
                  decoration: const InputDecoration(labelText: 'Teléfono'),
                  validator: (value) => value == null || value.isEmpty ? 'Introduce tu teléfono' : null,
                ),
                TextFormField(
                  controller: _birthYearController,
                  decoration: const InputDecoration(labelText: 'Año de nacimiento'),
                  keyboardType: TextInputType.number,
                  validator: (value) => value == null || value.isEmpty ? 'Introduce tu año de nacimiento' : null,
                ),
                TextFormField(
                  controller: _genderController,
                  decoration: const InputDecoration(labelText: 'Género'),
                  validator: (value) => value == null || value.isEmpty ? 'Introduce tu género' : null,
                ),
                TextFormField(
                  controller: _profileController,
                  decoration: const InputDecoration(labelText: 'Perfil'),
                  validator: (value) => value == null || value.isEmpty ? 'Introduce tu perfil' : null,
                ),
                TextFormField(
                  controller: _photoUrlController,
                  decoration: const InputDecoration(labelText: 'URL de foto de perfil (opcional)'),
                ),
                const SizedBox(height: 30),
                SizedBox(
                  width: double.infinity,
                  child: ElevatedButton(
                    onPressed: _registerUser,
                    child: const Text('Registrarse'),
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
