// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOBEoUIwHZpNK0eupvm8h50OBevpyggvs',
    appId: '1:885171300306:web:21fd45d6e4b391c7bf8a0b',
    messagingSenderId: '885171300306',
    projectId: 'serenalea-9ede9',
    authDomain: 'serenalea-9ede9.firebaseapp.com',
    storageBucket: 'serenalea-9ede9.firebasestorage.app',
    measurementId: 'G-FSPE903WXG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYsnST0Abb1awmJQU3v5e1_PlPSookz_U',
    appId: '1:885171300306:android:77820bdddca74dfbbf8a0b',
    messagingSenderId: '885171300306',
    projectId: 'serenalea-9ede9',
    storageBucket: 'serenalea-9ede9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA3DPNjjke00t6DlSv__KpDdXEJG7SPr0',
    appId: '1:885171300306:ios:10685243fe860569bf8a0b',
    messagingSenderId: '885171300306',
    projectId: 'serenalea-9ede9',
    storageBucket: 'serenalea-9ede9.firebasestorage.app',
    iosBundleId: 'com.example.serenalea',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDA3DPNjjke00t6DlSv__KpDdXEJG7SPr0',
    appId: '1:885171300306:ios:10685243fe860569bf8a0b',
    messagingSenderId: '885171300306',
    projectId: 'serenalea-9ede9',
    storageBucket: 'serenalea-9ede9.firebasestorage.app',
    iosBundleId: 'com.example.serenalea',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOBEoUIwHZpNK0eupvm8h50OBevpyggvs',
    appId: '1:885171300306:web:e8107a84bf671322bf8a0b',
    messagingSenderId: '885171300306',
    projectId: 'serenalea-9ede9',
    authDomain: 'serenalea-9ede9.firebaseapp.com',
    storageBucket: 'serenalea-9ede9.firebasestorage.app',
    measurementId: 'G-E13V6GQEKP',
  );
}
